// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0sYaLgXE0XgwkUTWOm5hkzGHpalsPi4M',
    appId: '1:441903825924:web:9036b1ef5fd1bd66002151',
    messagingSenderId: '441903825924',
    projectId: 'basicmedia-fc13c',
    authDomain: 'basicmedia-fc13c.firebaseapp.com',
    databaseURL: 'https://basicmedia-fc13c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'basicmedia-fc13c.appspot.com',
    measurementId: 'G-F325WSZ19E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUZq6hDm6OQLm7xS1ci0m9yduKe3ZBge4',
    appId: '1:441903825924:android:6039523bb2bd1441002151',
    messagingSenderId: '441903825924',
    projectId: 'basicmedia-fc13c',
    databaseURL: 'https://basicmedia-fc13c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'basicmedia-fc13c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBL2S0TH4xmelL3Zm7BWsfwIAgDs3wpzs',
    appId: '1:441903825924:ios:41406ca65c3ba26e002151',
    messagingSenderId: '441903825924',
    projectId: 'basicmedia-fc13c',
    databaseURL: 'https://basicmedia-fc13c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'basicmedia-fc13c.appspot.com',
    iosClientId: '441903825924-0vsja8o2ptt466flq4j3ar2lvu0rk6nc.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicMedia',
  );
}
